import { DeclarationData } from '@/types';

// 模拟申报要素数据
export const MOCK_DECLARATION_DATA: Record<string, DeclarationData> = {
  'import-first-normal': {
    header: {
      preEntryNo: 'ED2025011900001',
      customsNo: '',
      domesticConsignee: 'XX进出口贸易有限公司',
      domesticConsigneeCode: '4401960000',
      overseasConsignee: 'ABC TRADING CO., LTD',
      declarant: 'XX报关行',
      declarantCode: '4401980000',
      transportMode: '水路运输',
      transportModeCode: '2',
      vesselName: 'COSCO SHIPPING',
      voyageNo: '1234E',
      billNo: 'COSU1234567',
      tradeMode: '一般贸易',
      tradeModeCode: '0110',
      exemptionMode: '一般征税',
      exemptionModeCode: '101',
      countryOfOrigin: '日本',
      countryCode: '116',
      portOfLoading: '东京',
      portCode: '1333',
      transactionMode: 'CIF',
      freight: '502/50/2',
      insurance: '0.3/1',
      otherCharges: '',
      contractNo: 'CONTRACT2025001',
      packages: 100,
      packageType: '纸箱',
      grossWeight: 500,
      netWeight: 450,
      containerNo: 'COSU1234567',
      attachmentNo: '',
      marks: 'N/M',
    },
    items: [
      {
        itemNo: 1,
        goodsName: '汽车零部件',
        specs: '发动机总成 / 型号: ABC-123 / 品牌: XYZ / 用途: 维修',
        quantity: 10,
        unit: '个',
        unitCode: '035',
        countryOfOrigin: '日本',
        countryCode: '116',
        unitPrice: 5000,
        totalPrice: 50000,
        currency: '美元',
        currencyCode: '502',
        exemption: '照章征税',
        declarationElements: '用途:维修;品牌:XYZ;型号:ABC-123;成分为:铝合金',
      },
      {
        itemNo: 2,
        goodsName: '汽车零部件',
        specs: '刹车片 / 型号: BRAKE-456 / 品牌: XYZ / 用途: 维修',
        quantity: 50,
        unit: '套',
        unitCode: '137',
        countryOfOrigin: '日本',
        countryCode: '116',
        unitPrice: 100,
        totalPrice: 5000,
        currency: '美元',
        currencyCode: '502',
        exemption: '照章征税',
        declarationElements: '用途:维修;品牌:XYZ;型号:BRAKE-456;材质:半金属材料',
      },
    ],
  },
  'export-first-normal': {
    header: {
      preEntryNo: 'ED2025011900002',
      customsNo: '',
      domesticConsignee: 'XX进出口贸易有限公司',
      domesticConsigneeCode: '4401960000',
      overseasConsignee: 'XYZ TRADING CO., LTD',
      declarant: 'XX报关行',
      declarantCode: '4401980000',
      transportMode: '水路运输',
      transportModeCode: '2',
      vesselName: 'MAERSK LINE',
      voyageNo: '5678W',
      billNo: 'MARSK7654321',
      tradeMode: '一般贸易',
      tradeModeCode: '0110',
      exemptionMode: '一般征税',
      exemptionModeCode: '101',
      countryOfOrigin: '中国',
      countryCode: '142',
      portOfLoading: '深圳',
      portCode: '5217',
      transactionMode: 'FOB',
      freight: '',
      insurance: '',
      otherCharges: '',
      contractNo: 'CONTRACT2025002',
      packages: 200,
      packageType: '纸箱',
      grossWeight: 800,
      netWeight: 750,
      containerNo: 'MARSK7654321',
      attachmentNo: '',
      marks: 'XYZ/NO.1-200',
    },
    items: [
      {
        itemNo: 1,
        goodsName: 'LED灯具',
        specs: 'LED球泡灯 / 功率: 9W / 电压: 220V / 品牌: ABC',
        quantity: 1000,
        unit: '个',
        unitCode: '035',
        countryOfOrigin: '中国',
        countryCode: '142',
        unitPrice: 5,
        totalPrice: 5000,
        currency: '美元',
        currencyCode: '502',
        exemption: '照章征税',
        declarationElements: '品牌:ABC;型号:LED-9W;用途:照明;功率:9W;电压:220V',
      },
    ],
  },
};
